import React from 'react';
import ReactDOM from 'react-dom/client';
import { BrowserRouter, Link, NavLink, Route, Routes } from 'react-router-dom';
import './styles.css';

const email = 'bijalvp@gmail.com';
const projects = [
  ['stufd', 'Stufd', 'Food / QSR / Product Development', 'A food venture focused on craveable, delivery-friendly products, recipe development, costing, SOP planning, packaging, and QSR format exploration.'],
  ['recipe-cost-calculator', 'Recipe Cost Calculator', 'Web Tool / Food Business / Costing', 'A web-based recipe costing tool for ingredient costs, multi-step recipes, batch calculations, and practical food business planning.'],
  ['nse-intraday-screener', 'NSE Intraday Screener', 'Market Data / Web App', 'A web-based dashboard designed to turn early-session market data into a usable screening interface with filters and sortable views.']
];
const skills = ['Product concept development', 'MVP planning', 'Business model design', 'AI-assisted workflows', 'Website planning', 'Recipe costing', 'SOP creation', 'Clear business communication'];

function Header(){return <header className="site-header"><div className="container nav"><Link to="/" className="brand">Bijal Patel</Link><nav><NavLink to="/about">About</NavLink><NavLink to="/projects">Projects</NavLink><NavLink to="/skills">Skills</NavLink><NavLink to="/contact" className="nav-cta">Contact</NavLink></nav></div></header>}
function Footer(){return <footer className="footer"><div className="container footer-grid"><div><h2>Bijal Patel</h2><p>Founder and product builder working across AI workflows, web products, food ventures, and business execution.</p></div><div><h3>Pages</h3><Link to="/about">About</Link><Link to="/projects">Projects</Link><Link to="/skills">Skills</Link><Link to="/contact">Contact</Link></div><div><h3>Contact</h3><a href={`mailto:${email}`}>{email}</a></div></div></footer>}
function Hero(){return <section className="hero section"><div className="container hero-grid"><div><p className="eyebrow">Founder & Product Builder</p><h1>Bijal Patel</h1><p className="lead">Founder and product builder working at the intersection of AI, software, food ventures, and business execution.</p><p>I build and shape projects that combine product strategy, technology, content structure, and practical business execution.</p><div className="actions"><Link className="button primary" to="/projects">View Projects</Link><Link className="button ghost" to="/contact">Contact Me</Link></div></div><div className="hero-panel"><div>AI workflows</div><div>Web products</div><div>Food ventures</div><div>Business models</div></div></div></section>}
function ProjectCard({p}:{p:string[]}){return <article className="card project-card"><p className="eyebrow">{p[2]}</p><h3>{p[1]}</h3><p>{p[3]}</p><Link className="text-link" to={`/projects/${p[0]}`}>View case study →</Link></article>}
function PageHero({label,title,children}:{label:string;title:string;children:React.ReactNode}){return <section className="section page-hero"><div className="container narrow"><p className="eyebrow">{label}</p><h1>{title}</h1><p className="lead">{children}</p></div></section>}
function Cta(){return <section className="section"><div className="container cta"><div><p className="eyebrow">Contact</p><h2>Let’s build something thoughtful.</h2><p>For collaborations, product conversations, or venture discussions, write directly or send a message.</p></div><Link className="button light" to="/contact">Get in touch</Link></div></section>}
function Home(){return <><Hero/><section className="section intro"><div className="container split"><h2>Ideas made useful.</h2><p>My work moves across concept, structure, product logic, operations, content, and execution — turning loose ideas into systems that can be tested, improved, and used.</p></div></section><section className="section"><div className="container"><div className="section-head"><p className="eyebrow">Featured work</p><h2>Selected projects</h2></div><div className="grid three">{projects.map(p=><ProjectCard key={p[0]} p={p}/>)}</div></div></section><Cta/></>}
function About(){return <><PageHero label="About" title="A product-minded builder.">I am Bijal Patel, a founder and product builder based in India. My work sits at the intersection of AI-enabled workflows, software, food ventures, web tools, and business model design.</PageHero><section className="section"><div className="container two-col"><div className="portrait"><span>BP</span></div><div><h2>How I work</h2><p>Across projects, I am interested in how ideas become usable systems: a website, a product, a service, a recipe, a workflow, or a business model.</p><p>I work across concept, structure, product logic, content, operations, and execution.</p><div className="principles"><span>Clear structure</span><span>Practical execution</span><span>Measurable outcomes</span></div></div></div></section><Cta/></>}
function Projects(){return <><PageHero label="Projects" title="Selected work.">Three current projects showing product thinking across food, web tools, and market-data workflows.</PageHero><section className="section"><div className="container"><div className="grid three">{projects.map(p=><ProjectCard key={p[0]} p={p}/>)}</div></div></section></>}
function ProjectDetail(){const slug=location.pathname.split('/').pop();const p=projects.find(x=>x[0]===slug);if(!p)return <NotFound/>;return <><PageHero label={p[2]} title={p[1]}>{p[3]}</PageHero><section className="section"><div className="container two-col"><div><h2>Context</h2><p>{p[3]}</p></div><div className="card skill-detail"><h2>Role</h2><p>Founder / product owner / workflow designer.</p><h2>Status</h2><p>Current project.</p></div></div></section><Cta/></>}
function Skills(){return <><PageHero label="Skills" title="Capabilities.">Skills are grouped by how they create value: product strategy, AI-enabled workflows, food venture development, and clear communication.</PageHero><section className="section"><div className="container"><div className="grid two">{skills.map(s=><article className="card skill-detail" key={s}><h2>{s}</h2><p>Applied through practical planning, prototyping, documentation, and execution.</p></article>)}</div></div></section></>}
function Contact(){return <><PageHero label="Contact" title="Let’s build something thoughtful.">Have a project, collaboration, product idea, or venture conversation you would like to discuss?</PageHero><section className="section"><div className="container contact-grid"><div><h2>Write directly</h2><p>Send a message through the form or write directly to <a href={`mailto:${email}`}>{email}</a>.</p><div className="map-card"><span>India</span></div></div><form className="card form" name="contact" method="POST" action="/thank-you" data-netlify="true"><input type="hidden" name="form-name" value="contact"/><label>Name<input name="name" required/></label><label>Email<input name="email" type="email" required/></label><label>Project / enquiry type<select name="enquiryType"><option>Project conversation</option><option>Collaboration</option><option>Product discussion</option><option>Other</option></select></label><label>Message<textarea name="message" rows={6} required/></label><button className="button primary" type="submit">Send message</button></form></div></section></>}
function ThankYou(){return <section className="section page-hero"><div className="container narrow card skill-detail"><p className="eyebrow">Message sent</p><h1>Thank you.</h1><p className="lead">Your message has been submitted. You can also write directly to <a href={`mailto:${email}`}>{email}</a>.</p><Link className="button primary" to="/">Back home</Link></div></section>}
function NotFound(){return <section className="section page-hero"><div className="container narrow card skill-detail"><p className="eyebrow">404</p><h1>Page not found.</h1><Link className="button primary" to="/">Back home</Link></div></section>}
function App(){return <BrowserRouter><Header/><main><Routes><Route path="/" element={<Home/>}/><Route path="/about" element={<About/>}/><Route path="/projects" element={<Projects/>}/><Route path="/projects/:slug" element={<ProjectDetail/>}/><Route path="/skills" element={<Skills/>}/><Route path="/contact" element={<Contact/>}/><Route path="/thank-you" element={<ThankYou/>}/><Route path="*" element={<NotFound/>}/></Routes></main><Footer/></BrowserRouter>}
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
